# Generated by Django 4.0.7 on 2022-10-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_indexpage_poempage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poempage',
            name='poem_name',
        ),
    ]
