# Generated by Django 4.0.7 on 2022-10-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='poempage',
            name='intro',
            field=models.TextField(default='Default value for intros', max_length=20),
            preserve_default=False,
        ),
    ]
