# Generated by Django 4.0.7 on 2022-10-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_poempage_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poempage',
            name='intro',
            field=models.TextField(max_length=255),
        ),
    ]
