# Generated by Django 4.0.7 on 2022-10-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_poempage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='poempage',
            name='title_color',
            field=models.TextField(default='white', max_length=15),
        ),
    ]
