# Generated by Django 4.0.7 on 2022-10-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_poempage_title_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poempage',
            old_name='title_color',
            new_name='tc',
        ),
    ]
