# Generated by Django 4.0.7 on 2022-10-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_title_color_poempage_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poempage',
            name='tc',
            field=models.CharField(default='white', max_length=15),
        ),
    ]
